# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Response.proto',
  package='messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0eResponse.proto\x12\x08messages\"\xc2\x01\n\x08Response\x12>\n\x11hierarchical_step\x18\x01 \x03(\x0b\x32#.messages.Response.HierarchicalStep\x12\x1e\n\x16max_duration_step_name\x18\x02 \x02(\t\x12\"\n\x1amax_duration_step_duration\x18\x03 \x02(\x02\x1a\x32\n\x10HierarchicalStep\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08\x64uration\x18\x02 \x02(\x02')
)




_RESPONSE_HIERARCHICALSTEP = _descriptor.Descriptor(
  name='HierarchicalStep',
  full_name='messages.Response.HierarchicalStep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='messages.Response.HierarchicalStep.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='messages.Response.HierarchicalStep.duration', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=223,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='messages.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hierarchical_step', full_name='messages.Response.hierarchical_step', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_duration_step_name', full_name='messages.Response.max_duration_step_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_duration_step_duration', full_name='messages.Response.max_duration_step_duration', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_HIERARCHICALSTEP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=223,
)

_RESPONSE_HIERARCHICALSTEP.containing_type = _RESPONSE
_RESPONSE.fields_by_name['hierarchical_step'].message_type = _RESPONSE_HIERARCHICALSTEP
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(

  HierarchicalStep = _reflection.GeneratedProtocolMessageType('HierarchicalStep', (_message.Message,), dict(
    DESCRIPTOR = _RESPONSE_HIERARCHICALSTEP,
    __module__ = 'Response_pb2'
    # @@protoc_insertion_point(class_scope:messages.Response.HierarchicalStep)
    ))
  ,
  DESCRIPTOR = _RESPONSE,
  __module__ = 'Response_pb2'
  # @@protoc_insertion_point(class_scope:messages.Response)
  ))
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.HierarchicalStep)


# @@protoc_insertion_point(module_scope)
